services:
  firehose:
    build:
      context: ./
      dockerfile: Firehose.Dockerfile
    ports:
      - "8080:8080"

  kyoko:
    build:
      context: ./
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - MOTIONDB_URL=http://host.docker.internal:3000/
      - NEXT_PUBLIC_USER_NAME=maril
      - NEXT_PUBLIC_COMPANION_ID=companion_kyoko
      - NEXT_PUBLIC_FIREHOSE_URL=ws://localhost:8080/
      - NEXT_PUBLIC_MODEL_NAME=kyoko.vrm
      - NEXT_PUBLIC_IDLE_ANIMATION_URL=/idle.fbx
    volumes:
      - "./db:/app/db"
  aya:
    build:
      context: ./
    ports:
      - "3031:3031"
    environment:
      - PORT=3031
      - MOTIONDB_URL=http://host.docker.internal:3000/
      - NEXT_PUBLIC_USER_NAME=maril
      - NEXT_PUBLIC_COMPANION_ID=companion_aya
      - NEXT_PUBLIC_FIREHOSE_URL=ws://localhost:8080/
      - NEXT_PUBLIC_MODEL_NAME=aya.vrm
      - NEXT_PUBLIC_IDLE_ANIMATION_URL=/idle.fbx
    volumes:
      - "./db:/app/db"
