services:
  companion:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_COMPANION_ID=companion_kyoko
      - NEXT_PUBLIC_FIREHOSE_URL=ws://localhost:8080
      - NEXT_PUBLIC_MODEL_NAME=kyoko.vrm
      - NEXT_PUBLIC_VOICEVOX_URL=http://voicevox:50021
      - NEXT_PUBLIC_VOICEVOX_SPEAKER=1

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"
